/**
 * Country dial codes for the phone-number picker.
 *
 * MIRRORS aamantran_backend/src/lib/dialCodes.js -- the same way lib/constants.js
 * is mirrored into the admin panel. The backend copy is the authority: it is
 * what actually parses and stores a number. Keep the two in step.
 *
 * Codes are not unique (+1 covers the US, Canada and much of the Caribbean;
 * +7 covers Russia and Kazakhstan). That is fine here -- the picker shows one
 * row per country, and parsing only ever needs the dial code back.
 */
export type DialCode = readonly [dial: string, iso: string, name: string];

export const COUNTRIES: readonly DialCode[] = [
  ['+93', 'AF', 'Afghanistan'],
  ['+355', 'AL', 'Albania'],
  ['+213', 'DZ', 'Algeria'],
  ['+376', 'AD', 'Andorra'],
  ['+244', 'AO', 'Angola'],
  ['+1', 'AG', 'Antigua and Barbuda'],
  ['+54', 'AR', 'Argentina'],
  ['+374', 'AM', 'Armenia'],
  ['+297', 'AW', 'Aruba'],
  ['+61', 'AU', 'Australia'],
  ['+43', 'AT', 'Austria'],
  ['+994', 'AZ', 'Azerbaijan'],
  ['+1', 'BS', 'Bahamas'],
  ['+973', 'BH', 'Bahrain'],
  ['+880', 'BD', 'Bangladesh'],
  ['+1', 'BB', 'Barbados'],
  ['+375', 'BY', 'Belarus'],
  ['+32', 'BE', 'Belgium'],
  ['+501', 'BZ', 'Belize'],
  ['+229', 'BJ', 'Benin'],
  ['+1', 'BM', 'Bermuda'],
  ['+975', 'BT', 'Bhutan'],
  ['+591', 'BO', 'Bolivia'],
  ['+387', 'BA', 'Bosnia and Herzegovina'],
  ['+267', 'BW', 'Botswana'],
  ['+55', 'BR', 'Brazil'],
  ['+673', 'BN', 'Brunei'],
  ['+359', 'BG', 'Bulgaria'],
  ['+226', 'BF', 'Burkina Faso'],
  ['+257', 'BI', 'Burundi'],
  ['+855', 'KH', 'Cambodia'],
  ['+237', 'CM', 'Cameroon'],
  ['+1', 'CA', 'Canada'],
  ['+238', 'CV', 'Cape Verde'],
  ['+1', 'KY', 'Cayman Islands'],
  ['+236', 'CF', 'Central African Republic'],
  ['+235', 'TD', 'Chad'],
  ['+56', 'CL', 'Chile'],
  ['+86', 'CN', 'China'],
  ['+57', 'CO', 'Colombia'],
  ['+269', 'KM', 'Comoros'],
  ['+242', 'CG', 'Congo'],
  ['+243', 'CD', 'Congo (DRC)'],
  ['+506', 'CR', 'Costa Rica'],
  ['+225', 'CI', "Cote d'Ivoire"],
  ['+385', 'HR', 'Croatia'],
  ['+53', 'CU', 'Cuba'],
  ['+357', 'CY', 'Cyprus'],
  ['+420', 'CZ', 'Czechia'],
  ['+45', 'DK', 'Denmark'],
  ['+253', 'DJ', 'Djibouti'],
  ['+1', 'DM', 'Dominica'],
  ['+1', 'DO', 'Dominican Republic'],
  ['+593', 'EC', 'Ecuador'],
  ['+20', 'EG', 'Egypt'],
  ['+503', 'SV', 'El Salvador'],
  ['+240', 'GQ', 'Equatorial Guinea'],
  ['+291', 'ER', 'Eritrea'],
  ['+372', 'EE', 'Estonia'],
  ['+268', 'SZ', 'Eswatini'],
  ['+251', 'ET', 'Ethiopia'],
  ['+679', 'FJ', 'Fiji'],
  ['+358', 'FI', 'Finland'],
  ['+33', 'FR', 'France'],
  ['+594', 'GF', 'French Guiana'],
  ['+689', 'PF', 'French Polynesia'],
  ['+241', 'GA', 'Gabon'],
  ['+220', 'GM', 'Gambia'],
  ['+995', 'GE', 'Georgia'],
  ['+49', 'DE', 'Germany'],
  ['+233', 'GH', 'Ghana'],
  ['+350', 'GI', 'Gibraltar'],
  ['+30', 'GR', 'Greece'],
  ['+299', 'GL', 'Greenland'],
  ['+1', 'GD', 'Grenada'],
  ['+590', 'GP', 'Guadeloupe'],
  ['+1', 'GU', 'Guam'],
  ['+502', 'GT', 'Guatemala'],
  ['+224', 'GN', 'Guinea'],
  ['+245', 'GW', 'Guinea-Bissau'],
  ['+592', 'GY', 'Guyana'],
  ['+509', 'HT', 'Haiti'],
  ['+504', 'HN', 'Honduras'],
  ['+852', 'HK', 'Hong Kong'],
  ['+36', 'HU', 'Hungary'],
  ['+354', 'IS', 'Iceland'],
  ['+91', 'IN', 'India'],
  ['+62', 'ID', 'Indonesia'],
  ['+98', 'IR', 'Iran'],
  ['+964', 'IQ', 'Iraq'],
  ['+353', 'IE', 'Ireland'],
  ['+972', 'IL', 'Israel'],
  ['+39', 'IT', 'Italy'],
  ['+1', 'JM', 'Jamaica'],
  ['+81', 'JP', 'Japan'],
  ['+962', 'JO', 'Jordan'],
  ['+7', 'KZ', 'Kazakhstan'],
  ['+254', 'KE', 'Kenya'],
  ['+686', 'KI', 'Kiribati'],
  ['+965', 'KW', 'Kuwait'],
  ['+996', 'KG', 'Kyrgyzstan'],
  ['+856', 'LA', 'Laos'],
  ['+371', 'LV', 'Latvia'],
  ['+961', 'LB', 'Lebanon'],
  ['+266', 'LS', 'Lesotho'],
  ['+231', 'LR', 'Liberia'],
  ['+218', 'LY', 'Libya'],
  ['+423', 'LI', 'Liechtenstein'],
  ['+370', 'LT', 'Lithuania'],
  ['+352', 'LU', 'Luxembourg'],
  ['+853', 'MO', 'Macao'],
  ['+261', 'MG', 'Madagascar'],
  ['+265', 'MW', 'Malawi'],
  ['+60', 'MY', 'Malaysia'],
  ['+960', 'MV', 'Maldives'],
  ['+223', 'ML', 'Mali'],
  ['+356', 'MT', 'Malta'],
  ['+692', 'MH', 'Marshall Islands'],
  ['+596', 'MQ', 'Martinique'],
  ['+222', 'MR', 'Mauritania'],
  ['+230', 'MU', 'Mauritius'],
  ['+52', 'MX', 'Mexico'],
  ['+691', 'FM', 'Micronesia'],
  ['+373', 'MD', 'Moldova'],
  ['+377', 'MC', 'Monaco'],
  ['+976', 'MN', 'Mongolia'],
  ['+382', 'ME', 'Montenegro'],
  ['+212', 'MA', 'Morocco'],
  ['+258', 'MZ', 'Mozambique'],
  ['+95', 'MM', 'Myanmar'],
  ['+264', 'NA', 'Namibia'],
  ['+674', 'NR', 'Nauru'],
  ['+977', 'NP', 'Nepal'],
  ['+31', 'NL', 'Netherlands'],
  ['+687', 'NC', 'New Caledonia'],
  ['+64', 'NZ', 'New Zealand'],
  ['+505', 'NI', 'Nicaragua'],
  ['+227', 'NE', 'Niger'],
  ['+234', 'NG', 'Nigeria'],
  ['+850', 'KP', 'North Korea'],
  ['+389', 'MK', 'North Macedonia'],
  ['+47', 'NO', 'Norway'],
  ['+968', 'OM', 'Oman'],
  ['+92', 'PK', 'Pakistan'],
  ['+680', 'PW', 'Palau'],
  ['+970', 'PS', 'Palestine'],
  ['+507', 'PA', 'Panama'],
  ['+675', 'PG', 'Papua New Guinea'],
  ['+595', 'PY', 'Paraguay'],
  ['+51', 'PE', 'Peru'],
  ['+63', 'PH', 'Philippines'],
  ['+48', 'PL', 'Poland'],
  ['+351', 'PT', 'Portugal'],
  ['+1', 'PR', 'Puerto Rico'],
  ['+974', 'QA', 'Qatar'],
  ['+262', 'RE', 'Reunion'],
  ['+40', 'RO', 'Romania'],
  ['+7', 'RU', 'Russia'],
  ['+250', 'RW', 'Rwanda'],
  ['+1', 'KN', 'Saint Kitts and Nevis'],
  ['+1', 'LC', 'Saint Lucia'],
  ['+1', 'VC', 'Saint Vincent and the Grenadines'],
  ['+685', 'WS', 'Samoa'],
  ['+378', 'SM', 'San Marino'],
  ['+239', 'ST', 'Sao Tome and Principe'],
  ['+966', 'SA', 'Saudi Arabia'],
  ['+221', 'SN', 'Senegal'],
  ['+381', 'RS', 'Serbia'],
  ['+248', 'SC', 'Seychelles'],
  ['+232', 'SL', 'Sierra Leone'],
  ['+65', 'SG', 'Singapore'],
  ['+421', 'SK', 'Slovakia'],
  ['+386', 'SI', 'Slovenia'],
  ['+677', 'SB', 'Solomon Islands'],
  ['+252', 'SO', 'Somalia'],
  ['+27', 'ZA', 'South Africa'],
  ['+82', 'KR', 'South Korea'],
  ['+211', 'SS', 'South Sudan'],
  ['+34', 'ES', 'Spain'],
  ['+94', 'LK', 'Sri Lanka'],
  ['+249', 'SD', 'Sudan'],
  ['+597', 'SR', 'Suriname'],
  ['+46', 'SE', 'Sweden'],
  ['+41', 'CH', 'Switzerland'],
  ['+963', 'SY', 'Syria'],
  ['+886', 'TW', 'Taiwan'],
  ['+992', 'TJ', 'Tajikistan'],
  ['+255', 'TZ', 'Tanzania'],
  ['+66', 'TH', 'Thailand'],
  ['+670', 'TL', 'Timor-Leste'],
  ['+228', 'TG', 'Togo'],
  ['+676', 'TO', 'Tonga'],
  ['+1', 'TT', 'Trinidad and Tobago'],
  ['+216', 'TN', 'Tunisia'],
  ['+90', 'TR', 'Turkiye'],
  ['+993', 'TM', 'Turkmenistan'],
  ['+688', 'TV', 'Tuvalu'],
  ['+256', 'UG', 'Uganda'],
  ['+380', 'UA', 'Ukraine'],
  ['+971', 'AE', 'United Arab Emirates'],
  ['+44', 'GB', 'United Kingdom'],
  ['+1', 'US', 'United States'],
  ['+598', 'UY', 'Uruguay'],
  ['+998', 'UZ', 'Uzbekistan'],
  ['+678', 'VU', 'Vanuatu'],
  ['+58', 'VE', 'Venezuela'],
  ['+84', 'VN', 'Vietnam'],
  ['+967', 'YE', 'Yemen'],
  ['+260', 'ZM', 'Zambia'],
  ['+263', 'ZW', 'Zimbabwe'],
] as const;

/**
 * Pinned above the full list: India plus the diaspora markets this business
 * actually sells into. Everything else stays reachable below, so an unlisted
 * country never costs a sale -- this only makes the common choice one tap.
 */
export const POPULAR_ISO: readonly string[] = ['IN', 'US', 'CA', 'GB', 'AE', 'AU', 'SG', 'NZ', 'QA', 'SA', 'KW', 'OM', 'BH', 'MY', 'ZA', 'DE', 'NL', 'IE', 'CH'];

/** Every distinct dial code, longest first, for prefix matching. */
export const DIAL_CODES_BY_LENGTH: readonly string[] =
  Array.from(new Set(COUNTRIES.map((c) => c[0]))).sort((a, b) => b.length - a.length);

/** ISO -> dial, for defaulting the picker from a detected country. */
export const DIAL_BY_ISO: Record<string, string> =
  Object.fromEntries(COUNTRIES.map(([dial, iso]) => [iso, dial]));
